# Generated by Django 2.0.2 on 2018-02-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0002_auto_20180218_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='created_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
